import Head from 'next/head';
import VerticalBarChart from '../components/BarCharts/VerticalBarChart';

const Home = () => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Charts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-[90%] lg:w-[50%] mx-auto m-3">
        <VerticalBarChart />
      </div>
    </div>
  );
};

export default Home;
