import Head from 'next/head';

const Home = () => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Chart JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-bold text-2xl">Chart Js</h1>

      <div className="w-[90%] lg:w-[50%] mx-auto">
        <h2>sss</h2>
      </div>
    </div>
  );
};

export default Home;
